all : execl execv execvp execle

execl : 
	gcc execl.c -o execl

execv :
	gcc execv.c -o execv

execvp :
	gcc execvp.c -o execvp

execle :
	gcc execle.c -o execle

clean :
	rm -rf execl execv execvp execle
