CC=gcc

CFLAGS = -Wall -std=c99

all: hello1 hello2 hello3 hello4

hello1:
	${CC} ${CFLAGS} hello1.c -o hello1

hello2:
	${CC} ${CFLAGS} hello2.c -o hello2

hello3:
	${CC} ${CFLAGS} hello3.c -o hello3

hello4:
	${CC} ${CFLAGS} hello4.c -o hello4

clean:
	rm hello1 hello2 hello3 hello4




